### ISSUE TITLE
爬虫

### ISSUE THREAD

**Issue by linhhubku** [PFFFei/rent#27]
您好，您这个爬虫代码：scrapy crawl house(spider_name)，该在哪个地方运行呀，怎么报错了

**Comment by linhhubku** [comment]
![1656151209(1)](https://user-images.githubusercontent.com/106302611/175768754-b4a98e60-4b60-4511-bdaa-8414ad2e0a3f.png)

**Comment by linhhubku** [comment]
Traceback (most recent call last):
  File "D:\pycharm\rent-master\rentSpider\rentSpider\spiders\main.py", line 2, in <module>
    cmdline.execute("scrapy crawl house(spider_name)".split())
  File "D:\pycharm\venv\lib\site-packages\scrapy\cmdline.py", line 114, in execute
    settings = get_project_settings()
  File "D:\pycharm\venv\lib\site-packages\scrapy\utils\project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "D:\pycharm\venv\lib\site-packages\scrapy\settings\__init__.py", line 287, in setmodule
    module = import_module(module)
  File "D:\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\pycharm\rent-master\rentSpider\rentSpider\settings.py", line 17, in <module>
    django.setup()
  File "D:\pycharm\venv\lib\site-packages\django\__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "D:\pycharm\venv\lib\site-packages\django\conf\__init__.py", line 87, in __getattr__
    self._setup(name)
  File "D:\pycharm\venv\lib\site-packages\django\conf\__init__.py", line 74, in _setup
    self._wrapped = Settings(settings_module)
  File "D:\pycharm\venv\lib\site-packages\django\conf\__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "D:\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rent'

**Comment by linhhubku** [comment]
spider_name : 无法将“spider_name”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 20           
+ scrapy crawl house(spider_name)
+                    ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (spider_name:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
